Подготовил в выгрузке в add-reviews
AlinaProvotorova/java-filmorate pull request #19
Opened 2023-06-13 20:24 UTC by nikvitya

добавил валидацию в сервисный слой.
написал тесты на CRUD методы.

2023-06-13 20:48 UTC, AlinaProvotorova requested changes
Все отлично, посмотри коменты про валидацию)

2023-06-13 20:48 UTC, AlinaProvotorova commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    public Optional<List<Review>> getReviewByFilmId(Integer filmId, Integer count) {
Смотри здесь не нужен Optional т.к. ты возвращаешь список и он может быть пустой, исключения NullpointExeption здесь не должно возникнуть если я не ошибаюсь и в сервисе ты не проверяешьь filmId таким способом, оставлю коментарий в сервисе еще

2023-06-13 20:48 UTC, AlinaProvotorova commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +        ReviewValidate.validateId(review.getFilmId());
здесь так же добавь проверку на то что userId и filmId уже существуют в базе данных:
вот код как пример:
```
userStorage.getById(userId).orElseThrow(
                () -> new NotFoundException(String.format(USER_NOT_FOUND, userId)));
        userStorage.getById(friendId).orElseThrow(
                () -> new NotFoundException(String.format(USER_NOT_FOUND, friendId)));
```

2023-06-13 20:48 UTC, AlinaProvotorova commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +        }
вот здесь ты не проверяешь есть ли в базе такой фильм, а только то что будет этот список или нет, нужно просто добавить проверку до вызова функции как в примере выше я писала

2023-06-13 20:48 UTC, AlinaProvotorova commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
здесь тоже валидация юзера нужна и так же проверить есть ли такой отзыв в бд

2023-06-13 20:48 UTC, AlinaProvotorova commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
здесь тоже валидация юзера нужна и так же проверить есть ли такой отзыв в бд

2023-06-13 21:23 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +        ReviewValidate.validateId(review.getFilmId());
ок

2023-06-13 21:23 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    public Optional<List<Review>> getReviewByFilmId(Integer filmId, Integer count) {
пустой -это же не null... Optional.of(reviewList) - позволяет вернуть пустой список.

а Optional.empty() -в случае если filmid нет. и Обработать из в сервисе.

2023-06-13 21:31 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +        }
добавил

2023-06-13 21:44 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
добавил

2023-06-14 08:08 UTC, AlinaProvotorova approved these changes

2023-06-14 08:11 UTC, merged