Develop
AlinaProvotorova/java-filmorate pull request #22
Opened 2023-06-15 13:36 UTC by AlinaProvotorova

2023-06-16 10:53 UTC, AnastasiyaFomkina requested changes
Привет! Отличная работа, клево, что даже написали тесты на новый функционал 👍
Оставила несколько небольших комментариев, если непонятно, как избавиться от вложенных подзапросов - лучше не стесняться и обратиться к за помощью к наставникам.

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +//    Добавление нового отзыва.
Лучше писать [java doc](https://www.baeldung.com/javadoc) вместо обычных комментариев, так как они более информативны и красиво отображаются в IDE, что очень сильно помогает при разработке
<img width="727" alt="Снимок экрана 2023-06-16 в 07 24 24" src="https://github.com/AlinaProvotorova/java-filmorate/assets/43168217/2dca5609-f0df-4379-bfe8-52a8e440308e">

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +//            "useful": 20 // рейтинг полезности
Нужно удалить закомментированный код

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +        feedStorage.create(userId, id, "LIKE", "ADD");
Нужно сделать `eventType` и `operation` перечислениями, их проще поддерживать и расширять, плюс будет меньше ошибок с тем, что в строке можно передать практически все что угодно

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +    public ReviewServiceImpl(ReviewStorage reviewStorage,
Нужно подключать бины с помощью [@Autowired](https://www.baeldung.com/spring-autowire) либо [@RequiredArgsConstructor ](https://www.baeldung.com/spring-injection-lombok#:~:text=Constructor%20Injection%20With%20Lombok) из библиотеки `lombok`

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +        feedStorage.create(review.getUserId(), reviewWithId.getReviewId(), "REVIEW", "ADD");
`eventType` и `operation` должны быть перечислениями

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/LikesDbStorage.java
> +        String sql = "SELECT f.ID, f.NAME, f.RELEASE_DATE, f.DESCRIPTION, f.DURATION, f.RATING_ID " +
Нужно переписать запрос так, чтобы избавиться от множественных вложенных подзапросов

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    private final FilmDbStorage filmDbStorage;
Не используется

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +@Primary
А зачет тут `@Primary`?

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        String sql = "SELECT f.* FROM film f JOIN (" +
Нужно избавить от множества вложенных подзапросов

2023-06-16 10:53 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorageTest.java
> +    Review testReview;
Не хватает модификатора доступа

2023-06-16 11:44 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +//    Добавление нового отзыва.
спасибо, испарвил

2023-06-16 11:45 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +//            "useful": 20 // рейтинг полезности
исправил

2023-06-16 11:46 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/ReviewServiceImpl.java
> +    public ReviewServiceImpl(ReviewStorage reviewStorage,
написано было ,что когда один конструктор это необязательно . Добавил @Autowired

2023-06-16 11:48 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    private final FilmDbStorage filmDbStorage;
согласен) ушло в сервис)

2023-06-16 11:48 UTC, nikvitya commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +@Primary
убрал

2023-06-16 11:49 UTC, nikvitya commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorageTest.java
> +    Review testReview;
добавил

2023-06-17 16:57 UTC, AnastasiyaFomkina approved these changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Вы хорошо разобрались во взаимодействие между слоями сервис контроллер репозиторий. У вас получились отличные запросы к таблицам. И в целом видно, что вы подходили к работе с большой ответственностью, молодцы 🔥

2023-06-17 16:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/EventOperation.java
> +public enum EventOperation {
👍

2023-06-17 18:13 UTC, merged